notifications:
email: false
language: c++
before_install:
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -y qtdeclarative5-dev
    - sudo apt-get install -y  build-essential cmake libusb-1.0-0 libusb-1.0-0-dev

compiler: g++
script: make -f Makefile.top build

env:
  global:
   - secure: "GHcHPH3dkljU6ro8NsPcDe9YtC3FE4lOrBNUGqUKmN/VkGcf6bePVIx4LnHwfZI3XedUC3QOj/6f/qWK86zWtuJJA4RFBNR2kyZczCWV0nKDZ7zvWCMGomdq8ZeycBeYKEvlunJY5iVO8YWdQ6b1HJ2nt2oPaAUk4Axs8+rFjDw="

addons:
  coverity_scan:
    project:
      name: "Nitrokey/nitrokey-pro-firmware"
      description: "Build submitted via Travis CI"
    notification_email: george@nitrokey.com
    build_command_prepend: ""
    build_command:   "make -f Makefile.top build"
    branch_pattern: coverity_scan
